package com.aamo.exercisetracker.ui.theme

import androidx.compose.ui.graphics.Color

// Light
val primaryLight = Color(0xFF32628D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCFE4FF)
val onPrimaryContainerLight = Color(0xFF134A74)
val secondaryLight = Color(0xFF526070)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6E4F7)
val onSecondaryContainerLight = Color(0xFF3A4857)
val tertiaryLight = Color(0xFF695779)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF0DBFF)
val onTertiaryContainerLight = Color(0xFF514060)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F9FF)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFF8F9FF)
val onSurfaceLight = Color(0xFF191C20)
val surfaceVariantLight = Color(0xFFDEE3EB)
val onSurfaceVariantLight = Color(0xFF42474E)
val outlineLight = Color(0xFF73777F)
val outlineVariantLight = Color(0xFFC2C7CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEFF1F6)
val inversePrimaryLight = Color(0xFF9DCBFC)
val surfaceDimLight = Color(0xFFD8DAE0)
val surfaceBrightLight = Color(0xFFF8F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3F9)
val surfaceContainerLight = Color(0xFFECEEF4)
val surfaceContainerHighLight = Color(0xFFE6E8EE)
val surfaceContainerHighestLight = Color(0xFFE0E2E8)

// Dark
val primaryDark = Color(0xFFEAF0FF)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFA1C5FA)
val onPrimaryContainerDark = Color(0xFF000B1D)
val secondaryDark = Color(0xFFEAF0FF)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFFB8C3D8)
val onSecondaryContainerDark = Color(0xFF020C1A)
val tertiaryDark = Color(0xFFFFEDDB)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFFF2B86C)
val onTertiaryContainerDark = Color(0xFF140900)
val errorDark = Color(0xFFFFECE9)
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFFFFAEA4)
val onErrorContainerDark = Color(0xFF220001)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE1E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFFFFFFF)
val outlineDark = Color(0xFFEDF0F9)
val outlineVariantDark = Color(0xFFBFC2CB)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2E9)
val inverseOnSurfaceDark = Color(0xFF000000)
val inversePrimaryDark = Color(0xFF224977)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF4E5055)
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF1D2024)
val surfaceContainerDark = Color(0xFF2E3035)
val surfaceContainerHighDark = Color(0xFF393B41)
val surfaceContainerHighestDark = Color(0xFF44474C)